name: NUFORC Scrapping pipeline
on: [push]

env:
  FINAL_DATA_FILE: nuforc_reports_with_image_links.csv
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  scrape:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Download data files
        run: |
          aws s3 cp s3://ufo.camera/GeoLite2-City-CSV.zip data/external/

      - name: Run scrapping
        run: |
          dvc repro
